--- 
:filename: config.yml
:secret: 0dfc5ffb036833a07bc5716a6281fdb6e9c816c8
:soups: 
- soup
- soup/dynasnips
- soup/people
- soup/portfolio
- soup/system
- soup/system/dynasnips
:root_snip: FreeRange